Add user role
OpenRbt/share_business pull request #13
Opened 2023-05-09 06:00 UTC by Gurman520

2023-05-12 08:32 UTC, Exsolg commented on cmd/wash_admin/internal/app/app.go
> +const RoleEngineer = "engineer"
Создай отдельный тип для ролей:
type Role string

const (
	AdminRole             Role = "admin"
	UserRole                Role  = "user"
	EngineerRole         Role= "engineer"
)

2023-05-12 09:55 UTC, Exsolg approved these changes
lgtm!

2023-05-20 10:16 UTC, arsikirill requested changes

2023-05-20 10:16 UTC, arsikirill commented on cmd/wash_admin/internal/app/wash_server.go
> +		if eventErr != nil {
А если тут ошибка регистрация пройдет нормально и все будет работать?
К остальным методам, тот же вопрос.

2023-05-20 10:16 UTC, arsikirill commented on cmd/wash_admin/internal/conversions/wash_user.go
> +	case string(app.AdminRole):
case "admin"
а еще правильнее добавить в dal
const adminRole = "admin" 
.....

case adminRole:
r = app.AdminRole

и все это вынести в отдельную функцию.

2023-05-20 10:16 UTC, arsikirill commented on cmd/wash_admin/internal/conversions/wash_user.go
> +		panic(1)
Что за паника? как потом понять, что произошло?
Выведи нормальное сообщение.

2023-05-20 10:16 UTC, arsikirill commented on cmd/wash_admin/internal/conversions/wash_user.go
> +	switch dbWashUser.Role {
А где обратная конвертация для роли? из app в dal

2023-05-22 12:08 UTC, arsikirill requested changes

2023-05-22 12:08 UTC, arsikirill commented on cmd/wash_admin/internal/conversions/wash_user.go
> +		panic("Unknown role from db")
Добавь в вывод dbRole

2023-05-22 12:08 UTC, arsikirill commented on cmd/wash_admin/internal/conversions/wash_user.go
> +		panic("Unknown role from app")
Добавь в вывод appRole

2023-05-22 12:08 UTC, arsikirill commented on cmd/wash_admin/internal/app/WashUser.go
> +func (svc *WashServerSvc) UpdateUser(ctx context.Context, auth *Auth, userUpdate UpdateUser) error {
Так ты роль обновляешь или всего юзера?

2023-06-07 09:59 UTC, merged